# SonarQube Project Configuration
sonar.projectKey=ginobermudez76_LDCRuminaui
sonar.organization=ginobermudez76
sonar.host.url=https://sonarcloud.io
sonar.projectName=LDC Ruminaui
sonar.projectVersion=1.0

# Path to the source directories
sonar.sources=backend/app,backend/routes,frontend/src

# File encoding
sonar.sourceEncoding=UTF-8

# Exclude third-party libraries, generated resources, and binary files
sonar.exclusions=**/node_modules/**,**/vendor/**,**/dist/**,**/.angular/**,**/storage/**,**/.git/**,**/.vs/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.ico,**/*.webp,**/*.svg,**/*.pdf,**/*.woff,**/*.woff2,**/*.ttf,**/*.eot

# Language-specific configurations
sonar.javascript.environments=browser
sonar.php.validate=true
