# SonarQube Project Configuration
sonar.projectKey=LDCRuminaui
sonar.projectName=LDC Ruminaui
sonar.projectVersion=1.0

# Path to the source directories
sonar.sources=backend/app,backend/routes,frontend/src

# File encoding
sonar.sourceEncoding=UTF-8

# Exclude third-party libraries and generated resources
sonar.exclusions=**/node_modules/**,**/vendor/**,**/dist/**,**/.angular/**,**/storage/**,**/.git/**,**/.vs/**

# Language-specific configurations
sonar.javascript.environments=browser
sonar.php.validate=true
